[theme]
base = "dark"
primaryColor = "#F5C542"
backgroundColor = "#050505"
secondaryBackgroundColor = "#0A0A0A"
textColor = "#FFFFFF"
font = "sans serif"

[server]
runOnSave = false
maxUploadSize = 50
enableXsrfProtection = true

[browser]
gatherUsageStats = false
